name: .NET

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: WebSite - restore dependencies
        run: dotnet restore WebSite.sln

      - name: WebSite - Build
        run: dotnet build WebSite.sln --configuration Release --no-restore
        
      - name: WebSite - Launch
        run: cd ./WebSite/bin/Release/net8.0 && dotnet WebSite.dll &
        
      - name: Tests - restore dependencies
        run: dotnet restore TestProject_Calc/TestProject_Calc.csproj

      - name: Tests - Build
        run: dotnet build TestProject_Calc/TestProject_Calc.csproj --configuration Release --no-restore
        
      - name: Tests - Run
        run: dotnet test TestProject_Calc/TestProject_Calc.csproj --configuration Release --no-restore --verbosity Minimal
